# Generated by Django 5.1.4 on 2025-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('trip_date', models.DateField()),
            ],
        ),
    ]
