# Generated by Django 5.1.4 on 2025-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitMoneyApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
