# Generated by Django 5.1.4 on 2025-03-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitMoneyApis', '0003_alter_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='TripParticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=150)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now_add=True, null=True)),
                ('tripId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitMoneyApis.trip')),
            ],
        ),
    ]
