# Generated by Django 5.1.4 on 2025-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitMoneyApis', '0005_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
