# Generated by Django 5.1.4 on 2025-04-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitMoneyApis', '0006_alter_expenses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='trip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SplitMoneyApis.trip'),
            preserve_default=False,
        ),
    ]
