# Generated by Django 5.1.4 on 2025-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplitMoneyApis', '0007_expenses_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='payer_email',
            field=models.CharField(default='ak@mail.com', max_length=200),
            preserve_default=False,
        ),
    ]
